### ISSUE TITLE
metrics-sockstat.rb is broken in 5.0.0

### ISSUE THREAD

**Issue by rwky** [sensu-plugins/sensu-plugins-network-checks#131]
Throws an error
```
 /opt/sensu/embedded/bin/metrics-sockstat.rb 
/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-network-checks-5.0.0/bin/metrics-sockstat.rb:38:in `<class:MetricsSockstat>': uninitialized constant MetricsSockstat::Socket (NameError)
        from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-network-checks-5.0.0/bin/metrics-sockstat.rb:33:in `<top (required)>'
        from /opt/sensu/embedded/bin/metrics-sockstat.rb:23:in `load'
        from /opt/sensu/embedded/bin/metrics-sockstat.rb:23:in `<main>'
```
Previous versions work fine.

**Comment by nixwiz** [comment]
@asanchez1978 this was from your commit 6c7f9838 that was just rolled out in this release.

**Comment by sensu-discourse** [comment]
This issue has been mentioned on **Sensu Community**. There might be relevant details there:

https://discourse.sensu.io/t/class-metricssockstat-uninitialized-constant-metricssockstat-socket-nameerror/1634/2

**Comment by soichih** [comment]
For anyone trying to figure out how to downgrade from 5.0.0 to 4.0.0, here is what I did

```
/opt/sensu/embedded/bin/gem uninstall sensu-plugins-network-checks 
/opt/sensu/embedded/bin/gem install sensu-plugins-network-checks -v 4.0.0
```
