### ISSUE TITLE
metrics-ping.rb fails sometimes with Check failed to run: SIGUSR2

### ISSUE THREAD

**Issue by saravanakumar-periyasamy** [sensu-plugins/sensu-plugins-network-checks#42]
Here is the full stack trace

```
Check failed to run: SIGUSR2, ["/opt/sensu/embedded/lib/ruby/2.2.0/open3.rb:348:in `value'", 
"/opt/sensu/embedded/lib/ruby/2.2.0/open3.rb:348:in `block in capture2e'", 
"/opt/sensu/embedded/lib/ruby/2.2.0/open3.rb:199:in `popen_run'", 
"/opt/sensu/embedded/lib/ruby/2.2.0/open3.rb:188:in `popen2e'", 
"/opt/sensu/embedded/lib/ruby/2.2.0/open3.rb:335:in `capture2e'", "/etc/sensu/plugins/metrics-ping.rb:97:in `ping'", "/etc/sensu/plugins/metrics-ping.rb:105:in `run'", 
"/opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/sensu-plugin-1.2.0/lib/sensu-plugin/cli.rb:56:in `block in <class:CLI>'"]

```

**Comment by majormoses** [comment]
@saravanakumar-periyasamy Is this still happening? If so please give me the full command you are running and the version of the gem that is installed.

**Comment by majormoses** [comment]
closing due to inactivity.
