### ISSUE TITLE
check-whois-domain-expiration.rb doesn't work with .social domains

### ISSUE THREAD

**Issue by maticmeznar** [sensu-plugins/sensu-plugins-network-checks#61]
`$ check-whois-domain-expiration.rb -d test.social`
```Check failed to run: Unable to find a parser for property `expires_on', ["/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/whois-parser-1.0.0/lib/whois/parser.rb:350:in `delegate_property_to_parsers'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/whois-parser-1.0.0/lib/whois/parser.rb:312:in `expires_on'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/whois-parser-1.0.0/lib/whois/parser.rb:333:in `method_missing'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-network-checks-2.0.1/bin/check-whois-domain-expiration.rb:78:in `initialize'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugin-1.4.5/lib/sensu-plugin/cli.rb:57:in `new'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugin-1.4.5/lib/sensu-plugin/cli.rb:57:in `block in <class:CLI>'"]```

**Comment by majormoses** [comment]
Thanks for reporting this! Unfortunately this is another iteration of several issues that are unfortunately not part of this project and requires a change in the upstream projects :#59, https://github.com/weppos/whois-parser/issues/56. You should open issue here: https://github.com/weppos/whois-parser/issues and when it is fixed we can pull in the fix.

**Comment by maticmeznar** [comment]
@majormoses I think reporting bugs upstream is your responsibility. This plugin isn't even using the latest version of whois-parser (1.0.1) so I don't know whether upgrading might fix the problem. I'm not a Ruby programmer.

**Comment by majormoses** [comment]
I can certainly report it, that being said there are 2 active maintainers on plugins and neither of us work for sensu and as such I try to enlist help from the community where possible. Given that this affects you I figured you would be willing to report it.

**Comment by majormoses** [comment]
I did a quick skim and see nothing in: https://github.com/weppos/whois-parser/compare/v1.0.0...v1.0.1 to suggest that this is fixed upstream and needs a version bump.

**Comment by majormoses** [comment]
@maticmeznar per https://github.com/weppos/whois-parser/issues/64#issuecomment-335097215 looks like there are so many parsers missing that they do not even want an issue for it. We can keep this open until someone has the time to create a PR to add that functionality.

**Comment by maticmeznar** [comment]
@majormoses Thank you for your effort.
