### ISSUE TITLE
check-whois-domain-expiration-multi.rb v2.1.1 fails with "undefined local variable or method `domain_result'"

### ISSUE THREAD

**Issue by peterhoeg** [sensu-plugins/sensu-plugins-network-checks#67]
Running on version 2.1.1 I get the following error:

```
Check failed to run: undefined local variable or method `domain_result' for #, ["/nix/store/x8fgw5n17bna0khbwdh8qxpa7y0v2gd9-sensu-1.2.0/lib/ruby/gems/2.3.0/gems/sensu-plugins-network-checks-2.1.1/bin/check-whois-domain-expiration-multi.rb:97:in `block in expiration_results'", "/nix/store/x8fgw5n17bna0khbwdh8qxpa7y0v2gd9-sensu-1.2.0/lib/ruby/gems/2.3.0/gems/sensu-plugins-network-checks-2.1.1/bin/check-whois-domain-expiration-multi.rb:86:in `each'", "/nix/store/x8fgw5n17bna0khbwdh8qxpa7y0v2gd9-sensu-1.2.0/lib/ruby/gems/2.3.0/gems/sensu-plugins-network-checks-2.1.1/bin/check-whois-domain-expiration-multi.rb:86:in `expiration_results'", "/nix/store/x8fgw5n17bna0khbwdh8qxpa7y0v2gd9-sensu-1.2.0/lib/ruby/gems/2.3.0/gems/sensu-plugins-network-checks-2.1.1/bin/check-whois-domain-expiration-multi.rb:113:in `run'", "/nix/store/x8fgw5n17bna0khbwdh8qxpa7y0v2gd9-sensu-1.2.0/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.4.5/lib/sensu-plugin/cli.rb:58:in `block in '"]
```

Rolling back to 2.1.0 makes things work again.

**Comment by majormoses** [comment]
Thanks for the report, I think I see the problem let me get a a potential fix for you to test. Could you please include the redacted full command you are running? More often than not it really helps to see the command as sometimes people misuse options and it saves time looking for non-existent bugs.

**Comment by majormoses** [comment]
See if #70 solves your problems.

**Comment by peterhoeg** [comment]
#71 does the trick, thanks!
